# Project Information
site_name: tool_name
site_author: Samarth Mathur, Ph.D.
site_description: >-
  tool_name - LIquid Biopsy immunogEnetic vaRianT analYsis.
# Repository
repo_name: CCBR/tool_name
repo_url: https://github.com/CCBR/tool_name
edit_uri: https://github.com/CCBR/tool_name/edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-{{ now().year }} CCBR

# Configuration
theme:
  name: readthedocs
  locale: en
  custom_dir: docs/overrides
  #
# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  # version:
  #   provider: mike

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - About : index.md
  - Getting started: user-guide/getting-started.md
  - Usage: 
    - 1. Running the Pipeline: user-guide/run.md
    - 2. Expected Output: user-guide/output.md
    - 3. Preparing Files: user-guide/preparing-files.md
    - 4. Test Run: user-guide/test-info.md
  - FAQs: user-guide/troubleshooting.md
  - Contributions: user-guide/contributions.md
  - License: license.md
