# cluster configuration
###################################################################
__default__:
  gres: lscratch:96
  mem: 40g
  partition: ccr,norm
  time: 00-02:00:00
  threads: 2
  name: "{rule}.{wildcards}"
  output: "logs/{rule}.${{SLURM_JOBID}}.%j.{wildcards}.out"
  error: "logs/{rule}.${{SLURM_JOBID}}.%j.{wildcards}.err"
